<?php


namespace App\Http\Resources\Zds;


use App\Http\Resources\BaseCollection;

class OrderCollection extends BaseCollection
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}